site_name: jy-hf's learning site
site_description: An Experimental Package Management Solution for Python
repo_name: vra/mkdocs-material-example
repo_url: https://github.com/little612pea/jy-hf
copyright: Copyright &copy; 2023 jy Hu


nav:
  - Home: index.md
  - 1 数字逻辑设计:
    - 实验过程: 1 数字逻辑设计/数逻实验.md
    - 理论部分: 1 数字逻辑设计/数字逻辑设计 notes.md
  - 2 数据结构: 
    - 分课时笔记: 
      - 写在前面: 2 数据结构/webnotes/README.md
      - 第1周: 2 数据结构/webnotes/DS WEEK01.md
      - 第2周: 2 数据结构/webnotes/DS WEEK02.md
      - 第3周: 2 数据结构/webnotes/DS WEEK03.md
      - 第4周: 2 数据结构/webnotes/DS WEEK04.md
      - 第5周: 2 数据结构/webnotes/DS WEEK05.md
      - 第6周: 2 数据结构/webnotes/DS WEEK06.md
      - 第7周: 2 数据结构/webnotes/DS WEEK07.md
      - 第8周: 2 数据结构/webnotes/DS WEEK08.md
      - 第9周: 2 数据结构/webnotes/DS WEEK09.md
      - 第10周: 2 数据结构/webnotes/DS WEEK10.md
      - 第11周: 2 数据结构/webnotes/DS WEEK11.md
      - 第12周: 2 数据结构/webnotes/DS WEEK12.md
      - 第13周: 2 数据结构/webnotes/DS WEEK13.md
      - 第14周: 2 数据结构/webnotes/DS WEEK14.md
      - 第15周: 2 数据结构/webnotes/DS WEEK15.md
      - 总集篇: 2 数据结构/webnotes/Foundation-of-Data-Structure.md
    - 个人笔记: 2 数据结构/mynotes/FDS-notes.md
    - Labs & hw: 2 数据结构/labs&hw/FDS Lab&hw review.md
  - 3 ZJU-AI-ML: 
    - 课程笔记: 
      - 反向传播: 3 ZJU-AI-ML/feed forward and backward propagation.md
      - 赶快补课抄笔记: 3 ZJU-AI-ML/notes for ZJU-AI-ML.md
      - 一些截图: 3 ZJU-AI-ML/ML-zju.md
    - 课程Lab&hw: 3 ZJU-AI-ML/labs & hw review.md
  - 4 图像信息处理 DIP - 默写课~: 4 图像信息处理 DIP/DIP.md

  - Other:
    - Linux服务器运维(x)把玩(√): Others/linux 启动.md
    - CS61A: Others/CS61A-python.md

theme:
  name: material
  language: zh
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: cyan # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: cyan # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tasklist 
  #python markdown 无法显示内联公式，需要使用pymdownx.arithmatex
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - static/extra.css

extra_css:
  - "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css"
extra_javascript:
  - "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js"
  - "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js"
extra_javascript:
  - |
    document.addEventListener("DOMContentLoaded", function () {
      renderMathInElement(document.body, {
        delimiters: [
          { left: "$$", right: "$$", display: true },
          { left: "\\[", right: "\\]", display: true },
          { left: "$", right: "$", display: false },
          { left: "\\(", right: "\\)", display: false }
        ]
      });
    });
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
